// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Hv4r2oa59zWi_ECpf5bpLuHqXX7EL-g',
    appId: '1:629603594945:web:531ae3276c5550e7eb5a40',
    messagingSenderId: '629603594945',
    projectId: 'finstagram-908cd',
    authDomain: 'finstagram-908cd.firebaseapp.com',
    storageBucket: 'finstagram-908cd.appspot.com',
    measurementId: 'G-5F4NTBYLQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4yDHzABFzzLHaFm89r0MaNXtI35uHsRE',
    appId: '1:629603594945:android:7cd9d0fc4844d1dfeb5a40',
    messagingSenderId: '629603594945',
    projectId: 'finstagram-908cd',
    storageBucket: 'finstagram-908cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnoUL5ajdLdK3fzqTvkgH7xEnBPq_Yslc',
    appId: '1:629603594945:ios:7219f3ed7c5bfefdeb5a40',
    messagingSenderId: '629603594945',
    projectId: 'finstagram-908cd',
    storageBucket: 'finstagram-908cd.appspot.com',
    iosBundleId: 'com.example.finstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnoUL5ajdLdK3fzqTvkgH7xEnBPq_Yslc',
    appId: '1:629603594945:ios:7219f3ed7c5bfefdeb5a40',
    messagingSenderId: '629603594945',
    projectId: 'finstagram-908cd',
    storageBucket: 'finstagram-908cd.appspot.com',
    iosBundleId: 'com.example.finstagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Hv4r2oa59zWi_ECpf5bpLuHqXX7EL-g',
    appId: '1:629603594945:web:557b1c1eeb650904eb5a40',
    messagingSenderId: '629603594945',
    projectId: 'finstagram-908cd',
    authDomain: 'finstagram-908cd.firebaseapp.com',
    storageBucket: 'finstagram-908cd.appspot.com',
    measurementId: 'G-0WFPWXZGLC',
  );

}